version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: job_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: job_db
    ports:
      - "5411:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: job_backend
    restart: always
    ports:
      - "3411:3411"
    depends_on:
      postgres:
        condition: service_healthy

  job_form:
    image: nginx:alpine
    container_name: job_form
    restart: always
    ports:
      - "8010:80"
    volumes:
      - ./Job_form:/usr/share/nginx/html
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/index.html || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  job_posts:
    image: nginx:alpine
    container_name: job_posts
    restart: always
    ports:
      - "8011:80"
    volumes:
      - ./Job_Posts:/usr/share/nginx/html
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/index.html || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  default:
    name: job-network